"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
# بارگذاری متغیرهای محیطی از فایل .env
load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-(2yaro_#epo#s8b3wh#aem+w5-s=f^+a66z)qm*ug2p5-9@^5i")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    # Local apps
    'users.apps.UsersConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# کانفیگ دیتابیس برای سوئیچ به PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DB_NAME"),
        'USER': os.getenv("DB_USER"),
        'PASSWORD': os.getenv("DB_PASSWORD"),
        'HOST': os.getenv("DB_HOST"),
        'PORT': os.getenv("DB_PORT"),
    }
}

# معرفی مدل کاربر سفارشی (این خط حیاتیه!)
AUTH_USER_MODEL = 'users.User'
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Others
# تنظیمات اصلی Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # فعلا دسترسی پیش‌فرض رو روی حالتی می‌ذاریم که فقط افراد لاگین کرده بتونن APIها رو ببینن
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    # فعال‌سازی سیستم Throttling
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle', # برای کاربران مهمان (مبتنی بر IP)
        'rest_framework.throttling.UserRateThrottle'  # برای کاربران لاگین‌کرده (مبتنی بر User ID)
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',    # کاربران ناشناس نهایتا ۵ درخواست در دقیقه (عالی برای جلوگیری از اسپم ثبت‌نام/لاگین)
        'user': '60/minute'    # کاربران لاگین‌کرده نهایتا ۶۰ درخواست در دقیقه
    },
    # تنظیم سیستم تولید داکیومنت اتوماتیک
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
# تنظیمات اختصاصی دفترچه راهنمای API
SPECTACULAR_SETTINGS = {
    'TITLE': 'Parashop API',
    'DESCRIPTION': 'دفترچه راهنمای جامع APIهای پروژه فروشگاهی Parashop',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    # کامپوننت‌های امنیتی رو به سادگی به Swagger اضافه می‌کنه تا بتونی تو همون محیط تستی لاگین کنی
    'SECURITY': [{'BearerAuth': []}],
    'COMPONENTS': {
        'securitySchemes': {
            'BearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    }
}
# تنظیمات مربوط به عمر توکن‌ها (میتونی زمان‌ها رو بعدا تغییر بدی)
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'TOKEN_OBTAIN_SERIALIZER': 'users.serializers.CustomTokenObtainPairSerializer',
}
# =======================================================
# 🎨 Unfold Admin Panel Customization (Parashop)
# =======================================================
UNFOLD = {
    "SITE_TITLE": "Parashop",
    "SITE_HEADER": "Parashop",
    "SITE_URL": "/",

    # تنظیمات آیکون و لوگو (فعلا روی متریال دیزاین تنظیم شده، بعدا می‌توانی عکس‌های خودت را در پوشه static/ قرار دهی)
    "SITE_SYMBOL": "speed",  # آیکون متریال دیزاین کنار اسم سایت
    "SITE_ICON": {
        "light": lambda request: static("logo-light.svg"),
        "dark": lambda request: static("logo-dark.svg"),
    },

    # نمایش دکمه "مشاهده سایت" و تاریخچه تغییرات
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,

    # 🔵 پالت رنگی اختصاصی: آبی نئونی (Neon Blue) برای المان‌ها
    "COLORS": {
        "primary": {
            "50": "#eff6ff",
            "100": "#dbeafe",
            "200": "#bfdbfe",
            "300": "#93c5fd",
            "400": "#60a5fa",
            "500": "#00f0ff",  # Neon Blue (رنگ اصلی)
            "600": "#00d1ff",
            "700": "#1d4ed8",
            "800": "#1e40af",
            "900": "#1e3a8a",
            "950": "#172554",
        },
    },

    # 🔗 لینک‌های دسترسی سریع در سایدبار
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("میانبرهای توسعه"),
                "separator": True,
                "items": [
                    {
                        "title": _("مستندات API (Swagger)"),
                        "icon": "menu_book",
                        "link": "/api/docs/swagger/",
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("فرانت‌اند فروشگاه (Next.js)"),
                        "icon": "storefront",
                        "link": "http://localhost:3000",  # پورت استاندارد ریکت/نکست
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": _("سورس‌کد (GitHub)"),
                        "icon": "code",
                        "link": "https://github.com/your-username/Parashop-API",  # آدرس ریپازیتوری خودت را اینجا بگذار
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
}