# Generated by Django 6.0.6 on 2026-06-15 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='Title (Persian)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title (English)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'product_categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=255, verbose_name='Product Title (Persian)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Title (English)')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
                ('description_fa', models.TextField(verbose_name='Description (Persian)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description (English)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Price (IRT)')),
                ('inventory', models.PositiveIntegerField(default=0, verbose_name='Inventory / Stock')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'indexes': [models.Index(fields=['slug'], name='products_slug_5e91f2_idx'), models.Index(fields=['is_active', 'created_at'], name='products_is_acti_d5bdcf_idx')],
            },
        ),
    ]
